# Page settings
baseurl = "localhost:1313"
title = "LOCUS"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    login = "Partner Login"
    brand = "LOCUS"
    home = "Home"
    work = "Use cases"
    testimonials = "Technology"
    services = "Services"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Actionable analytics for the physical world."
    subtitle = 'Get your customer undersanding to the next level with an indoor positioning system capable of understanding how your customers navigate through your store, hospital, museum, airport.<br><br>Login:<a href="/login/"><br><i class="icon icon-user" href="/login/"></i></a>'

 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Gather data"
    description = "Colect data about how your customers navigate through your offline space using our sensors."
    url = "#"
    button = "Get In Touch"
    icon = "icon-layers"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Analyze data"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Take an action"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Use cases"
    description = "Use cases of businesses benefiting from location analytics."
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Retail"
      subtitle = "Understanding customer behaviour, store layout optimization and more"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Hospitals"
      subtitle = "Patient flow optimization, diseases tracking and more"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Airports"
      subtitle = "Visitor navigation, security and more"


  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Technology"
    description = "Learn about our Bloutooth based indoor positioning system and analytics tools."

  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "We provide an end-to-end solution that includes consulting, installation, maintanance and analytics."

    [[params.services.item]]
      title = "Consulting"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Installation"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Maintanance"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "Analytics"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "Let us take your customer analytics to the next level."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "250 - 13450 – 102nd Avenue, Surrey, BC V3T 0A3"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "email"],
        ["icon-globe", '<a href="" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Locus 2017'
